# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_menu_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('imagem',),
            },
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(db_index=True, max_length=200)),
                ('size', models.CharField(max_length=3)),
            ],
            options={
                'ordering': ('size',),
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('texto',)},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='titulo',
        ),
        migrations.AddField(
            model_name='menu',
            name='texto',
            field=models.CharField(db_index=True, default="menu", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='ref',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
